const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOAD_PONEYS = "LOAD_PONEYS";
const TOGGLE_VIEW_DELETED_PONEYS = "TOGGLE_VIEW_DELETED_PONEYS";
const ADD_PONEY = "ADD_PONEY";
const UPDATE_PONEY = "UPDATE_PONEY";
const DELETE_PONEY = "DELETE_PONEY";
const SET_LOADING_STATUS = "SET_LOADING_STATUS";

export {
  LOGIN,
  LOGOUT,
  LOAD_PONEYS,
  TOGGLE_VIEW_DELETED_PONEYS,
  ADD_PONEY,
  UPDATE_PONEY,
  DELETE_PONEY,
  SET_LOADING_STATUS
};
